# Generated by Django 6.0.1 on 2026-06-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='renting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
