# Generated by Django 6.0.1 on 2026-06-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_booking', '0002_renting_destination_renting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
