# Generated by Django 6.0.1 on 2026-06-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='image1_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image1_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rental_images/'),
        ),
        migrations.AddField(
            model_name='rental',
            name='image2_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image2_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='rental_images/'),
        ),
        migrations.AddField(
            model_name='rental',
            name='image3_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image3_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='rental_images/'),
        ),
        migrations.AddField(
            model_name='rental',
            name='image4_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image4_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='rental_images/'),
        ),
        migrations.AddField(
            model_name='rental',
            name='image5_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image5_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='rental_images/'),
        ),
        migrations.AddField(
            model_name='rental',
            name='image6_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='image6_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
