# Generated by Django 6.0.1 on 2026-05-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
    ]
