# Generated by Django 6.0.1 on 2026-05-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_room1_name_hotel_room1_price_hotel_room2_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_room1',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_room2',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
