# Generated by Django 6.0.1 on 2026-05-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_hotel_price_hotel_price_room1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price_room1',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_room2',
        ),
    ]
