# Generated by Django 6.0.1 on 2026-05-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_remove_hotel_price_room1_remove_hotel_price_room2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='room1_amenites',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room2_amenites',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
