# Generated by Django 6.0.1 on 2026-05-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
