# Generated by Django 6.0.1 on 2026-05-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_contact_us_check_in_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Us',
        ),
    ]
