# Generated by Django 6.0.1 on 2026-05-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('about_business', models.TextField(blank=True, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
