# Generated by Django 6.0.1 on 2026-05-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agent_number',
            field=models.CharField(default='0595407164', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
