# Generated by Django 6.0.1 on 2026-05-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_agent_number_booking_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agent_name',
            field=models.CharField(default='Ahmed Alhaj', max_length=100),
        ),
    ]
