# Generated by Django 6.0.1 on 2026-05-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('Master Bed', 'Room 1'), ('Regular', 'Room 2')], max_length=20),
        ),
    ]
