# Generated by Django 6.0.1 on 2026-05-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('Master Bed', 'Room 1'), ('Regular', 'Room 2')], max_length=20, null=True),
        ),
    ]
