# Generated by Django 6.0.1 on 2026-05-24 02:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_room_type'),
        ('hotels', '0009_hotel_room3_amenites_hotel_room3_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Hotel_Booking',
        ),
    ]
