# Generated by Django 6.0.1 on 2026-05-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_rename_booking_hotel_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_booking',
            name='room_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
