# Generated by Django 6.0.1 on 2026-06-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_hotel_booking_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_booking',
            name='user',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
